In [1]:
import numpy as np

In [2]:
arr = np.array([[2,3,4,5,64]], np.int64)

In [3]:
arr

array([[ 2,  3,  4,  5, 64]], dtype=int64)

In [4]:
arr

array([[ 2,  3,  4,  5, 64]], dtype=int64)

In [5]:
arr.shape


(1, 5)

In [6]:
arr.dtype


dtype('int64')

In [7]:
arr[0,4]=78

In [8]:
arr

array([[ 2,  3,  4,  5, 78]], dtype=int64)

# numpy array creation : using python object


In [9]:
myarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
myarray


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
myarray.size

9

In [12]:
myarray.shape

(3, 3)

In [13]:
myarray.dtype


dtype('int32')

# intrinsic array creation

In [14]:
zeros = np.zeros((2,10))

In [15]:
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
rng = np.arange(19)

In [17]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [18]:
rng.size

19

In [19]:
rng.shape

(19,)

In [20]:
rng.dtype

dtype('int32')

In [21]:
lsp = np.linspace(1,10,6)

In [22]:
lsp

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [23]:
emt = np.empty((2,7))

In [24]:
emt

array([[9.96248577e-312, 3.50786609e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 1.50008929e+248,
        4.50620083e-144],
       [4.82412328e+228, 1.04718130e-142, 5.04621361e+180,
        7.49779533e+247, 3.88625532e+285, 5.39631619e+228,
        2.61354267e-306]])

In [25]:
emtlike = np.empty_like(lsp)

In [26]:
emtlike

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [27]:
ide = np.identity(12 , np.int64)

In [28]:
ide

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int64)

In [29]:
ide.shape

(12, 12)

In [30]:
array = np.arange(100)

In [31]:
array.reshape(4,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [32]:
array = array.reshape(10,10)

In [33]:
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [34]:
array = array.ravel()

In [35]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [36]:
array.shape

(100,)

In [37]:
ary = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [38]:
ary

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
ary.sum(axis=0)

array([12, 15, 18])

In [40]:
ary.sum(axis=1)

array([ 6, 15, 24])

In [41]:
ary.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [42]:
ary.flat

In [43]:
for i in ary.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [44]:
ary.ndim

2

In [45]:
ary.size

9

In [46]:
ary.nbytes

36

In [47]:
ary

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
ary.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [49]:
ary.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [50]:
ary.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [51]:
ary

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
ary2 = np.array([[1,2,4],[5,6,7],[10,9,0]])

In [53]:
ary2

array([[ 1,  2,  4],
       [ 5,  6,  7],
       [10,  9,  0]])

In [54]:
ary + ary2

array([[ 2,  4,  7],
       [ 9, 11, 13],
       [17, 17,  9]])

In [55]:
ary * ary2

array([[ 1,  4, 12],
       [20, 30, 42],
       [70, 72,  0]])

In [56]:
np.sqrt(ary2)

array([[1.        , 1.41421356, 2.        ],
       [2.23606798, 2.44948974, 2.64575131],
       [3.16227766, 3.        , 0.        ]])

In [57]:
ary3 = np.array([[1,4,9],[16,25,36],[49,64,81]])

In [58]:
ary3

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [59]:
ary3 = np.sqrt(ary3)


In [60]:
ary3

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [61]:
ary4 = np.array(ary3, int)

In [62]:
ary4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
np.where(ary>8)

(array([2], dtype=int64), array([2], dtype=int64))

In [64]:
np.count_nonzero(ary4)

9

In [65]:
ary4[2,1] = 0

In [66]:
np.count_nonzero(ary4)

8

In [67]:
import sys

In [68]:
py_ar = [1,2,3,4]

In [69]:
np_ar  =np.array(py_ar)

In [70]:
sys.getsizeof(1)*len(py_ar)

112

In [71]:
np_ar.itemsize*np_ar.size

16